version = 1

exclude_patterns = [
 "src/sagemaker/tensorflow/tensorflow_serving/apis/model_service_pb2.py",
 "src/sagemaker/tensorflow/tensorflow_serving/apis/model_service_pb2_grpc.py"
]

test_patterns = [
 "tests/**"
]

[[analyzers]]
name = "python"
enabled = true
runtime_version = "3.x.x"

 [analyzers.meta]
 max_line_length = 100
 
